const restaurants = [
  { name: 'The Spice Route', cuisine: 'North Indian · Biryani', time: '25–30 min', rating: '4.7', offer: '40% off up to ₹100', image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=85', items: [['Butter Chicken', 'A creamy classic served with rice', 329, '🍗'], ['Paneer Tikka Masala', 'Charred paneer in tomato gravy', 269, '🍲'], ['Garlic Naan', 'Tandoor baked, butter brushed', 55, '🫓']] },
  { name: 'Pizza Corner', cuisine: 'Pizza · Italian', time: '30–35 min', rating: '4.5', offer: 'Free garlic bread above ₹499', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85', items: [['Farmhouse Pizza', 'Mushroom, onion, peppers & olives', 349, '🍕'], ['Pesto Pasta', 'Basil pesto, parmesan, cherry tomato', 259, '🍝']] },
  { name: 'Momo Nation', cuisine: 'Tibetan · Chinese', time: '20–25 min', rating: '4.6', offer: 'Flat ₹75 off on combos', image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=900&q=85', items: [['Steamed Veg Momos', 'Eight pieces with fiery chutney', 139, '🥟'], ['Chilli Garlic Noodles', 'Wok tossed noodles and vegetables', 189, '🍜']] }
];
let cart = [], activeRestaurant = restaurants[0], dash = 'restaurant';
const app = document.querySelector('#app'), money = n => `₹${n}`;
const foodImage = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=90';

function renderHome() {
  app.innerHTML = `<section class="new-hero"><div class="hero-noise"></div><div class="hero-copy"><span class="eyebrow light">Made for the neighbourhood</span><h1>Everything local.<br><i>Beautifully</i> close.</h1><p>From your favourite corner kitchen to tonight's essentials — your city, delivered with uncommon care.</p><div class="hero-search"><span>⌕</span><input placeholder="What are you looking for?"/><button onclick="showMenu(0)">Explore nearby</button></div><div class="hero-proof"><span>✦ 120+ local businesses</span><span>◉ Live in Raipur</span></div></div><div class="hero-visual"><div class="sun"></div><img src="${foodImage}" alt="A local Indian feast"/><span class="float-tag tag-one">Made nearby<br><b>Delivered warmly</b></span><span class="float-tag tag-two">★ 4.8 <small>community love</small></span><span class="olive-dot"></span></div></section>
  <section class="category-section"><div class="section-kicker">A city at your fingertips</div><div class="category-heading"><h2>What does your<br>day need?</h2><p>CityBites begins with food, but it was designed to make every local errand feel a little more human.</p></div><div class="category-rail"><button class="category-card big" onclick="showMenu(0)"><span>01</span><b>Food &<br>restaurants</b><i>↗</i></button><button class="category-card"><span>02</span><b>Fresh<br>groceries</b><i>Coming soon</i></button><button class="category-card"><span>03</span><b>Daily<br>essentials</b><i>Coming soon</i></button><button class="category-card warm"><span>04</span><b>Bakery &<br>flowers</b><i>Coming soon</i></button></div></section>
  <section class="featured"><div class="section-title editorial"><div><span class="eyebrow">Neighbourhood originals</span><h2>Worth leaving home for.<br>Now you don't have to.</h2></div><button class="round-link" onclick="showMenu(0)">View all <b>→</b></button></div><div class="feature-grid">${restaurants.map((r, i) => `<article class="featured-card card-${i}" onclick="showMenu(${i})"><div class="image-wrap"><img src="${r.image}" alt="${r.name}"/><span class="save">♡</span><span class="card-number">0${i + 1}</span></div><div class="featured-info"><div><h3>${r.name}</h3><p>${r.cuisine}</p></div><div class="rating">★ ${r.rating}</div></div><div class="card-footer"><span>${r.time} · ₹₹</span><strong>${r.offer}</strong></div></article>`).join('')}</div></section>
  <section class="specials"><div class="specials-image"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85" alt="Fresh food prepared locally"/><span>today<br>only</span></div><div class="specials-copy"><span class="eyebrow">The local edit</span><h2>Small-batch<br>joys, big-time<br>flavour.</h2><p>We asked the kitchens you already love to create something just for your Tuesday.</p><button class="ink-button" onclick="showMenu(0)">See today's specials <span>→</span></button></div><div class="specials-list"><div><b>01</b><span>Comfort bowls</span><em>from ₹179</em></div><div><b>02</b><span>After-hours bites</span><em>from ₹99</em></div><div><b>03</b><span>Sweet endings</span><em>from ₹129</em></div></div></section>
  <section class="journey"><div class="journey-title"><span class="eyebrow">Good things are in motion</span><h2>From their hands<br>to your table.</h2></div><div class="journey-steps"><article><span>01</span><h3>You find a local gem</h3><p>Discover the people and places that give your city its flavour.</p></article><article><span>02</span><h3>They make it fresh</h3><p>Your order goes straight to the kitchen — no middleman, no mystery.</p></article><article><span>03</span><h3>It comes to you</h3><p>A local delivery partner brings it over while it still feels made for you.</p></article></div></section>
  <section class="partner-callout"><div><span class="eyebrow light">For the people building this city</span><h2>Your regulars<br>are already online.</h2><p>Put your neighbourhood business on the map — with better tools, kinder fees and a brand your customers will remember.</p><button onclick="renderDash()">Explore partner portal <span>↗</span></button></div><div class="partner-stamp">LOCAL<br>FIRST<br><b>✦</b></div></section>
  <footer><a class="brand">✦ citybites</a><p>Neighbourhood commerce, thoughtfully connected.</p><div><button onclick="renderHome()">Discover</button><button onclick="renderOrders()">Orders</button><button onclick="renderDash()">Partner portal</button></div><small>© 2026 CityBites · made for smaller cities with bigger hearts</small></footer>`;
}

window.showMenu = i => { activeRestaurant = restaurants[i]; app.innerHTML = `<section class="page-head"><span class="eyebrow">${activeRestaurant.cuisine}</span><h1>${activeRestaurant.name}</h1><p class="meta">★ ${activeRestaurant.rating} · ${activeRestaurant.time} · Open now</p></section><section class="content"><div class="section-title"><h2>Popular picks</h2><button class="primary" onclick="toggleCart()">Basket (${cart.length})</button></div><div class="restaurant-grid">${activeRestaurant.items.map((x, j) => `<article class="restaurant"><div class="restaurant-img">${x[3]}</div><div class="r-info"><div class="r-title"><span>${x[0]}</span><span>${money(x[2])}</span></div><div class="meta">${x[1]}</div><button class="primary" style="margin-top:14px;padding:9px 14px" onclick="addItem(${j})">Add +</button></div></article>`).join('')}</div></section>`; };
window.addItem = i => { const x = activeRestaurant.items[i], found = cart.find(a => a.name === x[0]); found ? found.qty++ : cart.push({ name: x[0], desc: x[1], price: x[2], icon: x[3], qty: 1 }); renderCart(); toast(`${x[0]} added to your basket`); };
function renderCart() { const subtotal = cart.reduce((a, x) => a + x.price * x.qty, 0), fee = subtotal ? 29 : 0; document.querySelector('#cart-items').innerHTML = cart.length ? cart.map((x, i) => `<div class="cart-item"><div class="food-icon">${x.icon}</div><div><b>${x.name}</b><div class="small">${money(x.price)}</div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${i},1)">+</button></div></div><b>${money(x.price * x.qty)}</b></div>`).join('') : '<div class="empty">Your basket is waiting for something delicious.</div>'; document.querySelector('#cart-footer').innerHTML = cart.length ? `<div class="bill"><p><span>Item total</span><span>${money(subtotal)}</span></p><p><span>Delivery fee</span><span>${money(fee)}</span></p><p class="total"><span>To pay</span><span>${money(subtotal + fee)}</span></p><button class="primary checkout" onclick="placeOrder()">Place order · ${money(subtotal + fee)}</button></div>` : ''; }
window.changeQty = (i, n) => { cart[i].qty += n; if (!cart[i].qty) cart.splice(i, 1); renderCart(); }; window.toggleCart = () => document.querySelector('#cart').classList.toggle('open'); document.querySelector('.close-cart').onclick = toggleCart;
window.placeOrder = () => { cart = []; renderCart(); toggleCart(); renderOrders(); toast('Order placed! The restaurant has been notified.'); };
function renderOrders() { app.innerHTML = `<section class="page-head"><span class="eyebrow">Your order history</span><h1>Orders</h1></section><section class="order-wrap"><article class="order-card"><div><b>The Spice Route</b><div class="meta">Butter Chicken · Garlic Naan · ₹413</div><p class="meta">Order #CB-2894 · Today, 7:18 PM</p></div><span class="status">Out for delivery</span><div class="progress">${['Confirmed', 'Preparing', 'Picked up', 'On the way', 'Delivered'].map((x, i) => `<div class="dot ${i < 4 ? 'done' : ''}"><b></b>${x}</div>`).join('')}</div></article><article class="order-card"><div><b>Momo Nation</b><div class="meta">Steamed Veg Momos · ₹168</div><p class="meta">Order #CB-2751 · 12 Jul, 1:05 PM</p></div><span class="status">Delivered</span></article></section>`; }
function renderDash() { const isRest = dash === 'restaurant', title = isRest ? 'Restaurant dashboard' : dash === 'delivery' ? 'Delivery partner dashboard' : 'Platform admin'; const metrics = isRest ? [['Today’s sales', '₹12,480'], ['Orders today', '38'], ['Average order', '₹328'], ['Customer rating', '4.7 ★']] : dash === 'delivery' ? [['Today’s earnings', '₹780'], ['Completed', '8'], ['Online time', '5h 22m'], ['Customer rating', '4.9 ★']] : [['Total users', '12,482'], ['Live orders', '86'], ['Platform revenue', '₹74,320'], ['Active restaurants', '142']]; app.innerHTML = `<section class="page-head"><span class="eyebrow">CityBites partner portal</span><h1>${title}</h1></section><section class="dashboard"><div class="dash-tabs">${[['restaurant', 'Restaurant'], ['delivery', 'Delivery'], ['admin', 'Admin']].map(x => `<button class="${dash === x[0] ? 'active' : ''}" onclick="setDash('${x[0]}')">${x[1]}</button>`).join('')}</div><div class="metrics">${metrics.map(x => `<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small style="color:var(--green)">↑ 12.4% this week</small></div>`).join('')}</div><div class="panel"><h2>${isRest ? 'Incoming orders' : dash === 'delivery' ? 'Nearby delivery requests' : 'Orders requiring attention'}</h2>${[['#CB-2894', 'The Spice Route', '₹413'], ['#CB-2895', 'Pizza Corner', '₹629'], ['#CB-2896', 'Momo Nation', '₹168']].map((x, i) => `<div class="table-row"><b>${x[0]}</b><span>${isRest ? '2 items · ' + x[2] : x[1]}</span><span class="badge">${i ? 'New' : 'Ready for action'}</span><button class="action" onclick="toast('Order ${i ? 'accepted' : 'updated'} successfully')">${isRest ? 'Accept' : 'View'}</button></div>`).join('')}</div></section>`; }
window.setDash = x => { dash = x; renderDash(); }; function toast(t) { const e = document.querySelector('#toast'); e.textContent = t; e.className = 'toast show'; setTimeout(() => e.className = 'toast', 2800); }
document.querySelectorAll('.nav-link').forEach(x => x.onclick = () => { document.querySelectorAll('.nav-link').forEach(a => a.classList.remove('active')); x.classList.add('active'); if (x.dataset.page === 'home') renderHome(); if (x.dataset.page === 'orders') renderOrders(); if (x.dataset.page === 'dashboard') renderDash(); }); renderHome(); renderCart();
